"""tools/export_timeline.py on temporary fixtures. CI has no tracker access, and no tracker text is used here."""
import re
import subprocess
import sys
import tomllib

import pytest
from conftest import ROOT

from sitegen import content
from tools import export_timeline as ex

LINKS = ("# Links (fixture)\n\n| ID | Name / event | Year |\n|---|---|---|\n"
         "| HL-001 | fixture one | 1843 |\n| HL-002 | fixture two | 1867 |\n| HL-003 | fixture three | 1887 |\n")

ENTRY = '''[[confirmed]]
link = "{link}"
historian = "{historian}"
public = {public}
id = "{id}"
date = "{date}"
title = "Title {id}"
summary = "Summary {id}."
era = "ether"
class = "theory"
thread = ["ether"]
verified = "primary"
checked_by = "Historian"
checked_date = "2026-10-03"
{extra}
  [[confirmed.source]]
  key = "{key}"
  kind = "primary"
'''


def entry(link="HL-001", id="1843-hamilton-quaternions", date="1843-10-16", key="hamilton1865letter",
          historian="confirmed", public="true", extra=""):
    return ENTRY.format(link=link, id=id, date=date, key=key, historian=historian, public=public, extra=extra)


@pytest.fixture
def files(tmp_path, timeline_root):
    tracker = tmp_path / "tracker"
    tracker.mkdir()
    (tracker / "HISTORY-LINKS.md").write_text(LINKS, encoding="utf-8")
    out = tmp_path / "out" / "timeline.toml"

    def run(text, check_only=False, name="HISTORY-CONFIRMED.toml"):
        conf = tracker / name
        conf.write_text(text, encoding="utf-8")
        return ex.export(conf, tracker / "HISTORY-LINKS.md", out, root=timeline_root, check_only=check_only)

    run.out, run.root, run.tracker = out, timeline_root, tracker
    return run


def events(path):
    return tomllib.loads(path.read_text(encoding="utf-8"))["event"]


def test_only_confirmed_and_public_entries_export(files):
    text = (entry() + entry(link="HL-002", id="1867-kelvin-vortex-atoms", date="1867-02-18", key="kelvin1867vortex", public="false")
            + entry(link="HL-003", id="1887-michelson-morley", date="1887-11", key="michelson1887ether", historian="pending"))
    assert files(text) == 0
    assert [e["id"] for e in events(files.out)] == ["1843-hamilton-quaternions"]


def test_a_missing_public_flag_is_skipped(files):
    with pytest.raises(SystemExit, match="nothing to export"):
        files(entry().replace("public = true\n", ""))
    assert not files.out.exists()


def test_internal_keys_never_reach_the_output(files):
    files(entry())
    text = files.out.read_text(encoding="utf-8")
    assert "link" not in text and "historian" not in text and "public =" not in text and "HL-" not in text
    assert text.startswith("# GENERATED by tools/export_timeline.py")


def test_an_unknown_key_is_an_error(files):
    with pytest.raises(SystemExit, match="unknown field 'use_in_program'"):
        files(entry(extra='use_in_program = "x"'))
    with pytest.raises(SystemExit, match="source: unknown field 'cited_rows'"):
        files(entry().replace('kind = "primary"', 'kind = "primary"\n  cited_rows = "x"'))


def test_a_link_that_is_not_logged_is_refused(files):
    with pytest.raises(SystemExit, match="link does not name an entry"):
        files(entry(link="HL-999"))


@pytest.mark.parametrize("parts", [("_private", "HISTORY-CONFIRMED.toml"), ("a", "_private", "b", "HISTORY-CONFIRMED.toml")])
def test_a_private_path_is_refused(tmp_path, parts):
    path = tmp_path.joinpath(*parts)
    path.parent.mkdir(parents=True)
    path.write_text(entry(), encoding="utf-8")
    with pytest.raises(SystemExit, match="_private"):
        ex.export(path, path, tmp_path / "out.toml")


def test_a_path_in_an_ignored_folder_of_this_repo_is_refused():
    folder = ROOT / "tools" / "__pycache__"
    folder.mkdir(exist_ok=True)
    path = folder / "HISTORY-CONFIRMED.toml"
    path.write_text(entry(), encoding="utf-8")
    try:
        with pytest.raises(SystemExit, match="ignores"):
            ex.export(path, path, ROOT / "_site" / "unused.toml")
    finally:
        path.unlink()


def test_two_runs_are_byte_identical_and_check_passes(files):
    text = entry() + entry(link="HL-003", id="1887-michelson-morley", date="1887-11", key="michelson1887ether")
    files(text)
    first = files.out.read_bytes()
    files(text)
    assert files.out.read_bytes() == first and first.endswith(b"\n") and not first.endswith(b"\n\n") and b"\r" not in first
    assert files(text, check_only=True) == 0


def test_check_fails_after_a_manual_edit(files):
    files(entry())
    files.out.write_text(files.out.read_text(encoding="utf-8").replace("Summary", "Edited"), encoding="utf-8")
    assert files(entry(), check_only=True) == 1


def test_the_header_carries_no_input_hash(files):
    files(entry())
    text = files.out.read_text(encoding="utf-8")
    assert "sha256" not in text.lower() and not re.search(r"[0-9a-f]{64}", text, re.I)
    assert "".join(text.splitlines(keepends=True)[:2]) == ex.HEADER


def test_check_ignores_changes_to_non_public_rows(files):
    files(entry())
    hidden = entry(link="HL-002", id="1867-kelvin-vortex-atoms", date="1867-02-18", key="kelvin1867vortex", public="false")
    assert files("# a comment\n" + entry() + hidden, check_only=True) == 0


def test_check_still_fails_when_a_public_field_changes(files):
    files(entry())
    assert files(entry().replace('"Summary 1843-hamilton-quaternions."', '"A changed summary."'), check_only=True) == 1


def test_check_writes_nothing(files):
    assert files(entry(), check_only=True) == 1
    assert not files.out.exists()


def test_output_is_sorted_by_date_then_id(files):
    text = (entry(link="HL-003", id="1887-michelson-morley", date="1887-11", key="michelson1887ether")
            + entry(link="HL-002", id="1843-b", date="1843-10-16") + entry(id="1843-a"))
    files(text)
    assert [e["id"] for e in events(files.out)] == ["1843-a", "1843-b", "1887-michelson-morley"]


def test_a_private_term_blocks_the_write_and_names_the_id_only(files, monkeypatch, capsys):
    monkeypatch.setenv("FORBIDDEN_TERMS", "zzqx-corp")
    with pytest.raises(SystemExit) as exc:
        files(entry().replace('"Summary 1843-hamilton-quaternions."', '"Funded by ZZQX-Corp."'))
    message = str(exc.value) + capsys.readouterr().err
    assert "1843-hamilton-quaternions" in message and "zzqx" not in message.lower()
    assert not files.out.exists()


@pytest.mark.parametrize("summary", ["As logged in HL-001.", "See row R12.34.", "Checked by 00000000-1111-2222-3333-444444444444."])
def test_tracker_internal_ids_block_the_write(files, summary):
    with pytest.raises(SystemExit, match="tracker-internal id"):
        files(entry().replace('"Summary 1843-hamilton-quaternions."', f'"{summary}"'))
    assert not files.out.exists()


def test_the_acronym_blocks_the_write(files):
    with pytest.raises(SystemExit, match="spelled out"):
        files(entry().replace('"Summary 1843-hamilton-quaternions."', '"Used in AVE."'))


def test_the_output_passes_load_timeline(files):
    files(entry())
    (files.root / "content" / "timeline.toml").write_bytes(files.out.read_bytes())
    _, episodes = content.load(files.root)
    [ev] = content.load_timeline(files.root, episodes)
    assert ev.id == "1843-hamilton-quaternions" and ev.cls == "theory"


def test_output_that_fails_load_timeline_is_not_written(files):
    with pytest.raises(SystemExit, match="does not pass load_timeline"):
        files(entry(key="nobody1900nothing"))
    assert not files.out.exists()


def test_a_capitalised_bracket_is_refused(files):
    with pytest.raises(SystemExit, match=r"\[sic\]"):
        files(entry().replace('"Summary 1843-hamilton-quaternions."', '"He wrote [SIC] this."'))
    files(entry().replace('"Summary 1843-hamilton-quaternions."', '"He wrote [sic] this."'))
    assert "[sic]" in files.out.read_text(encoding="utf-8")


def test_the_verification_record_dates_bounds_and_claims_cross(files):
    text = (entry(date="1843-10-16", extra='date_basis = "event"\nclaims = ["ep001-c03"]')
            + entry(link="HL-002", id="1850-kelvin", date="", key="kelvin1867vortex",
                    extra='date_basis = "read"\nnot_before = "1845"\nnot_after = "1850"').replace('date = ""\n', "")
            + entry(link="HL-003", id="1887-michelson-morley", date="1887-11", key="michelson1887ether")
            .replace('verified = "primary"', 'verified = "secondary-only"'))
    files(text)
    out = {e["id"]: e for e in events(files.out)}
    assert out["1843-hamilton-quaternions"]["claims"] == ["ep001-c03"]
    assert out["1850-kelvin"]["date_basis"] == "read"
    assert (out["1850-kelvin"]["not_before"], out["1850-kelvin"]["not_after"]) == ("1845", "1850")
    assert out["1887-michelson-morley"]["verified"] == "secondary-only"
    assert all(e["checked_by"] == "Historian" and e["checked_date"] == "2026-10-03" for e in out.values())


@pytest.mark.parametrize("name", ["00000000-1111-2222-3333-444444444444", "historian bot 2", "Historian 2"])
def test_a_bot_shaped_checked_by_blocks_the_export(files, name):
    with pytest.raises(SystemExit):
        files(entry().replace('checked_by = "Historian"', f'checked_by = "{name}"'))
    assert not files.out.exists()


def test_no_date_is_derived(files):
    text = entry(date="1887-11", id="1887-michelson-morley", key="michelson1887ether", link="HL-003")
    files(text)
    [ev] = events(files.out)
    assert ev["date"] == "1887-11" and ev["checked_date"] == "2026-10-03"
    assert "2000" not in files.out.read_text(encoding="utf-8")  # the fixture bib's year never crosses


def test_an_unquoted_toml_date_crosses_as_the_same_iso_string(files):
    files(entry().replace('date = "1843-10-16"', "date = 1843-10-16"))
    assert 'date = "1843-10-16"' in files.out.read_text(encoding="utf-8")


# ------------------------------------------------------------------ the Historian's Markdown table
MD = ("# History confirmations (fixture)\n\n| HL id | Status | Original citation | Date checked | Note |\n|---|---|---|---|---|\n"
      "| HL-001 | confirmed-primary | fixture citation | 2026-10-03 | fixture note |\n"
      "| HL-002 | rejected | fixture citation | 2026-10-03 | fixture note |\n")


def test_the_markdown_confirmations_table_has_nothing_public_to_export(files, capsys):
    with pytest.raises(SystemExit, match="no public gate and no public wording"):
        files(MD, name="HISTORY-CONFIRMATIONS.md")
    assert "2 confirmation entries read, 1 confirmed, 0 confirmed and public" in capsys.readouterr().err
    assert not files.out.exists()


@pytest.mark.parametrize("change, message", [
    (("| HL-002 |", "| HL-999 |"), "link does not name an entry"),
    (("| HL-002 |", "| HL-001 |"), "second confirmation"),
    (("rejected", "maybe"), "unknown status"),
])
def test_bad_markdown_confirmations_are_refused(files, change, message):
    with pytest.raises(SystemExit, match=message):
        files(MD.replace(*change), name="HISTORY-CONFIRMATIONS.md")


def test_the_cli_takes_the_input_path_as_an_argument(files):
    conf = files.tracker / "HISTORY-CONFIRMATIONS.md"
    conf.write_text(MD, encoding="utf-8")
    run = subprocess.run([sys.executable, str(ROOT / "tools" / "export_timeline.py"), str(conf),
                          "--links", str(files.tracker / "HISTORY-LINKS.md"), "--out", str(files.out)], capture_output=True, text=True)
    assert run.returncode == 1 and "1 confirmed, 0 confirmed and public" in run.stderr
    assert not files.out.exists()


@pytest.mark.parametrize("key", ["title", "summary"])
@pytest.mark.parametrize("char", ["*", "_", "`"])
def test_markup_characters_in_titles_and_summaries_block_the_export(files, key, char):
    text = entry().replace(f'{key} = "{key.capitalize()} ', f'{key} = "{char}{key.capitalize()} ')
    assert f'{key} = "{char}' in text
    with pytest.raises(SystemExit, match=re.escape(f"{key} must be plain text (no *, _ or `); nothing written")):
        files(text)
    assert not files.out.exists()


# ------------------------------------------------------------------ reading links and their link-check gate
FULLTEXT = "https://archive.org/details/fixture/page/1/mode/1up"
LINK_GATE = 'links_checked_by = "Fixture checker"\nlinks_checked_date = "2026-10-04"'
FURTHER = ('\n  [[confirmed.further]]\n  title = "William Rowan Hamilton"\n  publisher = "MacTutor, University of St Andrews"\n'
           '  url = "https://mathshistory.st-andrews.ac.uk/Biographies/Hamilton/"\n')


def with_fulltext(text):
    return text.replace('kind = "primary"', f'kind = "primary"\n  fulltext_url = "{FULLTEXT}"')


@pytest.mark.parametrize("build", [with_fulltext, lambda t: t + FURTHER, lambda t: with_fulltext(t) + FURTHER])
def test_reading_links_need_the_link_check(files, build):
    with pytest.raises(SystemExit, match="links not checked"):
        files(build(entry()))
    with pytest.raises(SystemExit, match="links not checked"):
        files(build(entry(extra='links_checked_by = "Fixture checker"\nlinks_checked_date = "not a date"')))
    assert not files.out.exists()


def test_reading_links_cross_after_the_sources_and_the_gate_does_not(files):
    files(with_fulltext(entry(extra=LINK_GATE)) + FURTHER)
    text = files.out.read_text(encoding="utf-8")
    assert "links_checked" not in text and "Fixture checker" not in text
    assert text.endswith('  [[event.source]]\n  key = "hamilton1865letter"\n  kind = "primary"\n'
                         f'  fulltext_url = "{FULLTEXT}"\n\n  [[event.further]]\n  title = "William Rowan Hamilton"\n'
                         '  publisher = "MacTutor, University of St Andrews"\n'
                         '  url = "https://mathshistory.st-andrews.ac.uk/Biographies/Hamilton/"\n')
    [ev] = events(files.out)
    assert ev["source"][0]["fulltext_url"] == FULLTEXT and len(ev["further"]) == 1


def test_an_entry_without_reading_links_needs_no_link_check(files):
    files(entry())
    assert "further" not in files.out.read_text(encoding="utf-8")


def test_an_unknown_further_key_is_an_error(files):
    with pytest.raises(SystemExit, match="further: unknown field 'note'"):
        files(entry(extra=LINK_GATE) + FURTHER + '  note = "x"\n')


def test_a_further_link_that_fails_load_timeline_is_not_written(files):
    with pytest.raises(SystemExit, match="does not pass load_timeline.*not in FURTHER_HOSTS"):
        files(entry(extra=LINK_GATE) + FURTHER.replace("mathshistory.st-andrews.ac.uk", "example.org"))
    assert not files.out.exists()


def confirmations_for(timeline):
    """[[confirmed]] records that carry exactly the events of a timeline.toml, with every gate passed."""
    out = []
    for n, ev in enumerate(tomllib.loads(timeline)["event"], 1):
        lines = ["[[confirmed]]", f'link = "HL-{n:03d}"', 'historian = "confirmed"', "public = true"]
        if ev.get("further") or any("fulltext_url" in s for s in ev["source"]):
            lines.append(LINK_GATE)
        lines += [f"{k} = {ex._value(v, k)}" for k, v in ev.items() if k not in ("source", "further", "image")]
        if "image" in ev:
            lines += ["[confirmed.image]", 'image_checked_by = "Fixture checker"', 'image_checked_date = "2026-10-04"']
            lines += [f"{k} = {ex._value(v, k)}" for k, v in ev["image"].items()]
        for table, rows in (("source", ev["source"]), ("further", ev.get("further", []))):
            for row in rows:
                lines += [f"[[confirmed.{table}]]"] + [f"{k} = {ex._value(v, k)}" for k, v in row.items()]
        out.append("\n".join(lines) + "\n")
    return "\n".join(out)


def test_the_committed_timeline_is_exactly_what_the_exporter_writes(tmp_path):
    committed = ROOT / "content" / "timeline.toml"
    timeline = committed.read_text(encoding="utf-8")
    assert "[[event.further]]" in timeline and "fulltext_url" in timeline
    tracker = tmp_path / "tracker"
    tracker.mkdir()
    count = len(tomllib.loads(timeline)["event"])
    (tracker / "HISTORY-LINKS.md").write_text("| ID | Name |\n|---|---|\n" + "".join(f"| HL-{n:03d} | x |\n" for n in range(1, count + 1)),
                                              encoding="utf-8")
    (tracker / "HISTORY-CONFIRMED.toml").write_text(confirmations_for(timeline), encoding="utf-8")
    out = tmp_path / "timeline.toml"
    assert ex.export(tracker / "HISTORY-CONFIRMED.toml", tracker / "HISTORY-LINKS.md", out) == 0
    assert out.read_bytes() == committed.read_bytes()
    assert ex.export(tracker / "HISTORY-CONFIRMED.toml", tracker / "HISTORY-LINKS.md", committed, check_only=True) == 0


def test_the_plain_text_check_covers_title_and_summary_only(files):
    files(entry(extra='oneliner = "A snake_case name stays as written."'))
    assert events(files.out)[0]["oneliner"] == "A snake_case name stays as written."
