#!/usr/bin/env python3
"""Export Historian-confirmed, public timeline entries into content/timeline.toml. Standard library only.

    python3 tools/export_timeline.py CONFIRMATIONS --links HISTORY-LINKS.md [--out content/timeline.toml] [--check]

CONFIRMATIONS is the Historian's file from a read-only checkout of the tracker, in either form:
  *.toml  one [[confirmed]] table per entry: link, historian, public, then exactly the timeline.toml event fields
  *.md    the Historian's status table (HL id | Status | ...). It records confirmations only: no public gate and no
          public wording, so nothing in it can export on its own.
HISTORY-LINKS.md is read only for its id column, to check that every confirmation names a logged link.

An entry exports only if historian = "confirmed" and public = true. Only allowlisted fields cross; nothing else from
either input is ever copied. Output is deterministic: sorted by date, then id, fixed key order, LF, and no timestamp or
input hash. --check exits 1 if the output file would change. Before anything is written, the
text is scanned for the private forbidden terms, internal tracker ids and the framework's acronym, then loaded with
content.load_timeline against a copy of content/.
"""
import argparse
import datetime
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import check  # noqa: E402
from sitegen import content  # noqa: E402

EVENT_FIELDS = ("id", "date", "date_basis", "end", "circa", "not_before", "not_after", "title", "summary", "oneliner", "people",
                "era", "class", "thread", "verified", "checked_by", "checked_date", "claims", "episodes", "related")
SOURCE_FIELDS = ("key", "kind", "locator", "doi", "url", "note")
GATE_FIELDS = ("link", "historian", "public")
MD_STATUSES = {"confirmed-primary", "confirmed-secondary-only", "corrected", "rejected"}
HEADER = ("# GENERATED by tools/export_timeline.py from Historian-confirmed entries. Do not edit by hand.\n"
          "# Everything in this file is public.\n")
# Tracker-internal identifiers that must never reach the site: link ids, register rows, bot ids.
INTERNAL = (re.compile(r"\bHL-\d+"), re.compile(r"\bR\d+\.\d+"),
            re.compile(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b", re.I))


class ExportError(SystemExit):
    def __init__(self, message):
        super().__init__(f"export_timeline: {message}")


# ---------------------------------------------------------------- inputs
def refuse_path(path: Path):
    """Inputs come from a tracker checkout. Never _private/, never an ignored folder of this repo."""
    resolved = path.resolve()
    if "_private" in path.parts or "_private" in resolved.parts:
        raise ExportError(f"refusing to read {path}: it is under a _private folder")
    if resolved.is_relative_to(ROOT):
        ignored = subprocess.run(["git", "-C", str(ROOT), "check-ignore", "-q", str(resolved)], capture_output=True)
        if ignored.returncode == 0:
            raise ExportError(f"refusing to read {path}: it is in a folder this repository ignores")
    if not resolved.is_file():
        raise ExportError(f"{path} does not exist")
    return resolved


def _table_rows(text):
    """Cells of every Markdown table row, header and divider rows included."""
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("|") and line.endswith("|"):
            yield [c.strip() for c in line[1:-1].split("|")]


def link_ids(path: Path):
    """The id column of HISTORY-LINKS.md. Nothing else in the file is read into the export."""
    return {cells[0] for cells in _table_rows(path.read_text(encoding="utf-8")) if re.fullmatch(r"HL-\d{3,}", cells[0])}


def read_confirmations(path: Path):
    """[(position, record)], where record holds the gate fields and, for TOML, the public payload."""
    text = path.read_text(encoding="utf-8")
    if path.suffix == ".toml":
        try:
            raw = tomllib.loads(text).get("confirmed", [])
        except tomllib.TOMLDecodeError as exc:
            raise ExportError(f"{path.name}: {exc}") from None
        if not isinstance(raw, list) or not all(isinstance(r, dict) for r in raw):
            raise ExportError(f"{path.name}: expected [[confirmed]] tables")
        return list(enumerate(raw, 1))
    if path.suffix == ".md":
        rows, header = [], None
        for cells in _table_rows(text):
            if header is None:
                if cells[:2] == ["HL id", "Status"]:
                    header = cells
                continue
            if set("".join(cells)) <= set("-: "):
                continue
            hl, status = cells[0], cells[1]
            if status not in MD_STATUSES:
                raise ExportError(f"{path.name}, row {len(rows) + 1}: unknown status (one of {', '.join(sorted(MD_STATUSES))})")
            rows.append((len(rows) + 1, {"link": hl, "historian": status}))
        if header is None:
            raise ExportError(f"{path.name}: no 'HL id | Status' table found")
        return rows
    raise ExportError(f"{path.name}: expected a .toml or .md confirmations file")


def select(records, ids, source_name):
    """Gate and allowlist: only confirmed + public entries, only schema fields. Unknown keys are errors."""
    allowed = set(GATE_FIELDS) | set(EVENT_FIELDS) | {"source"}
    chosen, confirmed, seen = [], 0, set()
    for pos, record in records:
        where = f"{source_name}, entry #{pos}" + (f" (id {record['id']})" if isinstance(record.get("id"), str) else "")
        unknown = sorted(set(record) - allowed)
        if unknown:
            raise ExportError(f"{where}: unknown field {unknown[0]!r}")
        link = record.get("link")
        if not isinstance(link, str) or link not in ids:
            raise ExportError(f"{where}: link does not name an entry in HISTORY-LINKS.md")
        if link in seen:
            raise ExportError(f"{where}: a second confirmation for the same link")
        seen.add(link)
        historian = record.get("historian")
        if historian == "confirmed" or (isinstance(historian, str) and historian.startswith("confirmed-")):
            confirmed += 1
        if historian != "confirmed" or record.get("public") is not True:
            continue
        event = {k: record[k] for k in EVENT_FIELDS if k in record}
        sources = record.get("source", [])
        if not isinstance(sources, list) or not all(isinstance(s, dict) for s in sources):
            raise ExportError(f"{where}: source must be [[confirmed.source]] tables")
        for s in sources:
            bad = sorted(set(s) - set(SOURCE_FIELDS))
            if bad:
                raise ExportError(f"{where}, source: unknown field {bad[0]!r}")
        event["source"] = [{k: s[k] for k in SOURCE_FIELDS if k in s} for s in sources]
        chosen.append(event)
    return chosen, confirmed


# ---------------------------------------------------------------- TOML out
def _string(value):
    out = []
    for ch in value:
        if ch in '"\\':
            out.append("\\" + ch)
        elif ch in "\b\t\n\f\r":
            out.append({"\b": "\\b", "\t": "\\t", "\n": "\\n", "\f": "\\f", "\r": "\\r"}[ch])
        elif ord(ch) < 0x20 or ord(ch) == 0x7f:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _value(value, where):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _string(value)
    if isinstance(value, datetime.date) and not isinstance(value, datetime.datetime):
        return _string(value.isoformat())
    if isinstance(value, list):
        return "[" + ", ".join(_value(v, where) for v in value) + "]"
    raise ExportError(f"{where}: unsupported value type {type(value).__name__}")


def _sort_key(event):
    for key in ("date", "not_before", "not_after"):
        value = event.get(key)
        if isinstance(value, datetime.date):
            value = value.isoformat()
        if isinstance(value, str) and content.PARTIAL_DATE.fullmatch(value):
            return content.date_key(value), str(event.get("id", ""))
    return (9999, 99, 99), str(event.get("id", ""))  # undated: load_timeline refuses it below


def render_event(event):
    where = f"event {event.get('id')}"
    lines = ["[[event]]"] + [f"{k} = {_value(event[k], where)}" for k in EVENT_FIELDS if k in event]
    for s in event["source"]:
        lines += ["", "  [[event.source]]"] + [f"  {k} = {_value(s[k], where)}" for k in SOURCE_FIELDS if k in s]
    return "\n".join(lines) + "\n"


def render(events):
    blocks = [render_event(e) for e in sorted(events, key=_sort_key)]
    return HEADER + "".join("\n" + b for b in blocks)


# ---------------------------------------------------------------- guards
def guard(events):
    """Refuse anything that must not ship. Messages name the event id, never the matched text."""
    terms = check.forbidden_terms()
    if not terms:
        print("WARN no private forbidden-term list found (FORBIDDEN_TERMS or _private/forbidden.txt): that rule is skipped",
              file=sys.stderr)
    for event in events:
        name = event.get("id", "?")
        block = render_event(event)
        data = block.encode("utf-8").lower()
        if any(t.encode() in data for t in terms):
            raise ExportError(f"event {name}: a term that must never appear on a channel surface is in this entry; nothing written")
        if any(p.search(block) for p in INTERNAL):
            raise ExportError(f"event {name}: carries a tracker-internal id; nothing written")
        if check.ACRONYM.search(block):
            raise ExportError(f"event {name}: the framework's name must be spelled out (three-letter acronym found); nothing written")
        for key in ("title", "summary", "oneliner"):
            if isinstance(event.get(key), str) and check.PLACEHOLDER.search(event[key]):
                raise ExportError(f"event {name}: capitalised bracket in {key} (write [sic] in lowercase); nothing written")
            if isinstance(event.get(key), str) and content.MARKUP.search(event[key]):
                raise ExportError(f"event {name}: {key} must be plain text (no *, _ or `); nothing written")
        checked_by = event.get("checked_by")
        if not isinstance(checked_by, str) or not content.CHECKED_BY.fullmatch(checked_by):
            raise ExportError(f"event {name}: checked_by must be a public display name; nothing written")


def validate(text, root: Path):
    """Load the output exactly as the build will, against a temporary copy of content/."""
    with tempfile.TemporaryDirectory() as tmp:
        shutil.copytree(root / "content", Path(tmp) / "content")
        (Path(tmp) / "content" / "episodes").mkdir(exist_ok=True)
        (Path(tmp) / "content" / "timeline.toml").write_text(text, encoding="utf-8", newline="\n")
        try:
            _, episodes = content.load(Path(tmp))
            return content.load_timeline(Path(tmp), episodes)
        except SystemExit as exc:
            raise ExportError(f"the output does not pass load_timeline: {exc}; nothing written") from None


# ---------------------------------------------------------------- main
def export(confirmations: Path, links: Path, out: Path, root: Path = ROOT, check_only=False):
    confirmations, links = refuse_path(confirmations), refuse_path(links)
    ids = link_ids(links)
    if not ids:
        raise ExportError(f"{links.name}: no link ids found")
    records = read_confirmations(confirmations)
    events, confirmed = select(records, ids, confirmations.name)
    print(f"{len(records)} confirmation entries read, {confirmed} confirmed, {len(events)} confirmed and public", file=sys.stderr)
    if not events:
        why = (" This file records confirmations only: it has no public gate and no public wording (id, title, summary)."
               if confirmations.suffix == ".md" else "")
        raise ExportError(f"no entry is both confirmed and public, so there is nothing to export.{why} Nothing written.")
    guard(events)
    text = render(events)
    validate(text, root)
    current = out.read_bytes() if out.is_file() else None
    if check_only:
        if current != text.encode("utf-8"):
            print(f"{out.name} is out of date: rerun tools/export_timeline.py without --check", file=sys.stderr)
            return 1
        print(f"{out.name} is current ({len(events)} events)", file=sys.stderr)
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(text.encode("utf-8"))
    print(f"wrote {len(events)} events to {out}", file=sys.stderr)
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("confirmations", type=Path, help="the Historian's confirmations file (.toml or .md)")
    parser.add_argument("--links", type=Path, required=True, help="HISTORY-LINKS.md, for the link id cross-check")
    parser.add_argument("--out", type=Path, default=ROOT / "content" / "timeline.toml", help="default: content/timeline.toml")
    parser.add_argument("--check", action="store_true", help="exit 1 if the output file would change; write nothing")
    args = parser.parse_args(argv)
    return export(args.confirmations, args.links, args.out, check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
